Repository cslant/blog-api-package, pull requests merged in 2024-07, with the labels that each got.

#11 feat/setup-workflow-to-test-code-style
  workflows/phpstan.yml
Labels: enhancement

#12 fix: setup workflow to test code style
  .github/pull_request_template.md
  .github/workflows/phpstan.yml
Labels: bug

#16 Fix/styleci ignore
  .styleci.yml
Labels: bug

#19 feat: update composer info
  composer.json
Labels: feature request

#21 feat/workflow-test-composer
  .github/workflows/setup_test.yml
Labels: enhancement

#18 Feature/get exist apis
  .scrutinizer.yml
  README.md
  phpstan-baseline.neon
  routes/blog-api.php
  src/Http/Controllers/Base/BaseCategoryController.php
  src/Http/Controllers/Base/BaseTagController.php
  src/Http/Controllers/CategoryController.php
  src/Http/Controllers/TagController.php
Labels: enhancement, feature request

#23 Fix/move base code to core
  phpstan-baseline.neon
  src/Http/Controllers/Base/BaseCategoryController.php
  src/Http/Controllers/Base/BasePostController.php
  src/Http/Controllers/Base/BaseTagController.php
  src/Http/Controllers/CategoryController.php
  src/Http/Controllers/PostController.php
  src/Http/Controllers/TagController.php
  src/Models/Traits/IsIncrementing.php
Labels: enhancement, feature request
