Repository cslant/blog-api-package, pull requests merged in 2025-03, with the labels that each got.

#36 feat: create a response schema for the 400 error
  src/OpenApi/Responses/Errors/BadRequestResponseSchema.php
Labels: feature request

#37 Feat add status response schema #16
  src/OpenApi/Responses/Errors/ErrorNotFoundResponseSchema.php
  src/OpenApi/Responses/Success/SuccessCreateResponseSchema.php
Labels: feature request

#39 Update phpstan.yml
  .github/workflows/phpstan.yml
Labels: bug, dependencies

#46 #44 feat: add AuthorSchema model
  src/OpenApi/Schemas/Models/AuthorSchema.php
Labels: feature request

#47 #44 feat: change property for AuthorSchema
  src/OpenApi/Schemas/Resources/Author/AuthorModelResourceSchema.php
Labels: feature request

#49 Feature/author model schema #44
  src/OpenApi/Schemas/Resources/Author/AuthorModelResourceSchema.php
Labels: feature request

#48 feat: create tag model and resource schemas
  src/OpenApi/Schemas/Models/TagSchema.php
  src/OpenApi/Schemas/Resources/Tag/TagModelResourceSchema.php
Labels: feature request

#45 Feature/post model and resource schemas #42
  src/Http/Controllers/CategoryController.php
  src/OpenApi/Schemas/Models/AuthorSchema.php
  src/OpenApi/Schemas/Models/PostSchema.php
  src/OpenApi/Schemas/Resources/Category/CategoryListResourceSchema.php
  src/OpenApi/Schemas/Resources/Category/CategoryModelResourceSchema.php
  src/OpenApi/Schemas/Resources/Post/PostListResourceSchema.php
  src/OpenApi/Schemas/Resources/Post/PostModelResourceSchema.php
Labels: feature request

#50 Feat/api docs for tag actions-#41
  src/Http/Controllers/TagController.php
Labels: feature request

#51 #43 feat: add api docs for post actions
  src/Http/Controllers/PostController.php
Labels: documentation, feature request

#52 #38 feat: add api and docs for views count
  routes/blog-api.php
  src/Http/Controllers/Actions/Post/ViewCountAction.php
  src/Http/Resources/ViewCountResource.php
  src/OpenApi/Schemas/Resources/Post/ViewCountResourceSchema.php
Labels: documentation, feature request

#59 #43 feat: add description for each array
  src/Http/Controllers/PostController.php
Labels: feature request

#60 #55 feat: add api docs categories filters
  src/Http/Controllers/CategoryController.php
Labels: feature request

#61 #57 feat: Change the system tag resource logic
  src/Providers/BlogApiServiceProvider.php
Labels: feature request

#62 #54 feat: add profile user and list posts
  phpstan-baseline.neon
  routes/blog-api.php
  src/Http/Actions/Author/AuthorAction.php
  src/Http/Actions/Post/ViewCountAction.php
  src/Http/Controllers/CategoryController.php
  src/Http/Controllers/PostController.php
  src/Http/Controllers/TagController.php
  src/Http/Resources/Author/AuthorResource.php
  src/Http/Resources/Author/AuthorWithPostResource.php
  src/Http/Resources/Category/CategoryResource.php
  src/Http/Resources/Category/ListCategoryResource.php
  src/Http/Resources/Post/ListPostResource.php
  src/Http/Resources/Post/ListPostResourceCollection.php
  src/Http/Resources/Post/PostResource.php
  src/Http/Resources/Post/ViewCountResource.php
  src/Http/Resources/Tag/TagResource.php
  src/OpenApi/Schemas/Resources/Author/AuthorWithPostResourceSchema.php
  src/Providers/BlogApiServiceProvider.php
Labels: feature request

#65 fix: remove extend and add trait HasHttpResponse
  src/Http/Actions/Author/AuthorAction.php
  src/Http/Actions/Post/ViewCountAction.php
Labels: bug, api

#63 Feature/add get list post pagination filter by tag #43
  phpstan-baseline.neon
  routes/blog-api.php
  src/Http/Actions/Author/AuthorGetProfileAction.php
  src/Http/Actions/Post/PostGetByTagsAction.php
  src/Http/Actions/Post/PostGetViewCountAction.php
  src/Http/Resources/Author/AuthorWithPostResource.php
  src/Services/PostService.php
Labels: documentation, feature request, api

#66 #28 feat: get all author with posts count
  routes/blog-api.php
  src/Http/Actions/Author/AuthorGetListAction.php
  src/Http/Resources/Author/ListAuthorResource.php
  src/OpenApi/Schemas/Resources/Author/ListAuthorResourceSchema.php
  src/Services/AuthorService.php
Labels: documentation, feature request, api

#67 Feature/get list blog by category in center home page #27
  routes/blog-api.php
  src/Http/Actions/Post/PostGetCustomFiltersAction.php
  src/Services/PostService.php
Labels: feature request, api

#68 fix: update docs for order by
  common/helpers.php
  composer.json
  src/Http/Actions/Post/PostGetCustomFiltersAction.php
  src/Services/PostService.php
Labels: documentation, api, backend

#71 feat: add filters for tags and categories
  routes/blog-api.php
  src/Http/Actions/Tag/TagGetFiltersAction.php
  src/Http/Controllers/CategoryController.php
  src/Http/Resources/Category/ListCategoryResource.php
  src/Http/Resources/Tag/TagResource.php
  src/OpenApi/Schemas/Resources/Category/CategoryModelResourceSchema.php
  src/OpenApi/Schemas/Resources/Tag/TagModelResourceSchema.php
  src/Services/CategoryService.php
  src/Services/PostService.php
  src/Services/TagService.php
  src/Supports/FilterTag.php
Labels: feature request

#72 Feature/update filter tags and categories
  src/Http/Actions/Tag/TagGetFiltersAction.php
  src/Http/Controllers/CategoryController.php
Labels: bug

#75 #53: docs: edit description to make documentation clear.
  src/Http/Actions/Post/PostStoreViewCountAction.php
Labels: documentation
